---
variables:
  IMAGE_TAG: "latest"

stages:
  - build
  - test
  - deploy

image: docker:latest

build-task:
  stage: build
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - ls -la /var/run/docker.sock
    - ps aux | grep docker
    - groups
    - docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG .
    - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
test-task:
  stage: test
  script:
    - echo "test"

deploy-task:
  stage: deploy
  script:
    - docker pull $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker start -p 9999:9999 $IMAGE_NAME
...
