---
variables:
  IMAGE_TAG: "latest"
#  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

include:
  - template: "Code-Quality.gitlab-ci.yml"
#  - template: "Verify/Accessibility.gitlab-ci.yml"
  - template: "Security/SAST.gitlab-ci.yml"
  - template: "Security/Secret-Detection.gitlab-ci.yml"
  - template: "Security/Dependency-Scanning.gitlab-ci.yml"
  - template: "Security/Container-Scanning.gitlab-ci.yml"
  - template: "Security/SAST-IaC.latest.gitlab-ci.yml"
#  - template: "Security/License-Scanning.gitlab-ci.yml"

stages:
  - build
  - test
  - accessibility
  - deploy

image: docker:latest

before_script:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

build-task:
  stage: build
  variables:
     DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
  only:
    - master
    - dev

code_quality:
    stage: test
    image: golang:1.24-alpine
    before_script:
      - apk add --no-cache jq
    script:
      - echo '[]' > gl-code-quality-report.json
      -  | 
       if [ $(find . -name "*_test.go" | wc -l) -eq 0 ]; then 
       jq '. += [{"description": "No tests found", "severity": "major", "fingerprint": "no-tests", "location": { "path": ".", "lines": { "begin": 1 } } } ]' gl-code-quality-report.json > tmp.json && mv tmp.json gl-code-quality-report.json 
       fi
    artifacts:
      reports:
        codequality: gl-code-quality-report.json
      paths:
        - gl-code-quality-report.json
      when: always
    needs: ["build-task"]

static_analysis:
  image: golang:1.24-alpine
  before_script:
    - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
    - go install golang.org/x/lint/golint@latest
    - go install github.com/go-critic/go-critic/cmd/gocritic@latest
    - go install honnef.co/go/tools/cmd/staticcheck@latest
  script:
    - go vet ./... || true
    - staticcheck ./... || true
    - gocritic check ./... || true
    - gocyclo -over 15 . || true
  needs: ["build-task"]
  only:
    - master
  #  - dev

unit_tests:
  image: golang:1.24-alpine
  before_script:
    - go install github.com/jstemmer/go-junit-report@latest
  script:
    - go test -v ./... 2>&1 | go-junit-report > unit_test_results.xml || true
  artifacts:
    reports:
      junit: unit_test_results.xml
    paths:
      - unit_test_results.xml
  needs: ["build-task"]
  only:
    - master
  #  - dev

#a11y:
#  variables:
#    a11y_urls: "http://127.0.0.1:9999"
#  before_script:
#    - |
#      rm -f gl-accessibility-report.json
#  artifacts:
#    reports:
#      accessibility: gl-accessibility-report.json
#    paths:
#      - "gl-accessibility-report.json"

#license_scanning:
#  stage: test
#  image: registry.gitlab.com/gitlab-org/security-products/license-scanning:latest
#  before_script:
#    - rm -f gl-license-scanning-report.json
#  script:
#    - /run.sh
#  artifacts:
#    reports:
#      license_scanning: gl-license-scanning-report.json
#    paths:
#      - "gl-license-scanning-report.json"
#  allow_failure: true

iac-scanning:
  stage: test
  variables:
    SAST_IAC_DOCKERFILE_ENABLED: "true"
  before_script:
    - rm -f gl-iac-sast-report.json
  artifacts:
    reports:
      sast_iac: gl-iac-sast-report.json
    paths:
      - "gl-iac-sast-report.json"

container_scanning:
  stage: test
  variables:
    CS_IMAGE: "docker.io/$DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG"
  before_script:
    - |
      rm -f gl-container-scanning-report.json
  artifacts:
    reports:
      codequality: gl-container-scanning-report.json
    paths:
      - "gl-container-scanning-report.json"
  needs: [ "build-task" ]

secret_detection:
  stage: test
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"
    CI_DEBUG_TRACE: "true"
  before_script:
    - |
      rm -f gl-secret-detection-report.json
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
    paths:
      - "gl-secret-detection-report.json"

sast:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"
  before_script:
    - |
      rm -f gl-sast-report.json
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - "gl-sast-report.json"

dependency_scanning:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"
  before_script:
    - |
      rm -f gl-dependency-scanning-report.json
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
    paths:
      - "gl-dependency-scanning-report.json"

test-task:
  stage: test
  script:
    - echo "test"
  needs: ["build-task"]
  only:
    - master
    - dev

deploy-task:
  stage: deploy
  script:
    - docker rm --force $IMAGE_NAME
    - docker pull $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker run -d -p 9999:9999 --name $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME
  needs: ["test-task"]
  only:
    - master
    - dev
...
