---
variables:
  IMAGE_TAG: "latest"
#  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  a11y_urls: "http://127.0.0.1:9999"

include:
  - template: "Code-Quality.gitlab-ci.yml"
  - template: "Verify/Accessibility.gitlab-ci.yml"
  - template: "Security/SAST.gitlab-ci.yml"
  - template: "Security/Secret-Detection.gitlab-ci.yml"
  - template: "Security/Dependency-Scanning.gitlab-ci.yml"

stages:
  - build
  - test
  - accessibility
  - deploy

image: docker:latest

before_script:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

.create_empty_report:
  after_script:
    - |
      REPORT_FILE="$REPORT_FILENAME"
      echo "Test extends block within extends"
      if [ ! -f "$REPORT_FILE" ]; then
        echo "Creating empty report: $REPORT_FILE"
        echo '{
          "version": "2.0",
          "vulnerabilities": [],
          "remediations": [],
          "scan": {
            "scanner": {
              "name": "'"${SCANNER_NAME}"'",
              "version": "'"${CI_SERVER_VERSION:-unknown}"'"
            },
            "start_time": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'",
            "end_time": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'",
            "status": "success"
          }
        }' > "$REPORT_FILE"
      fi

build-task:
  stage: build
  variables:
     DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
  only:
    - master
    - dev

code_quality:
    stage: test
    image: golang:1.24-alpine
    before_script:
      - apk add --no-cache jq
    script:
      - echo '[]' > gl-code-quality-report.json
      -  | 
       if [ $(find . -name "*_test.go" | wc -l) -eq 0 ]; then 
       jq '. += [{"description": "No tests found", "severity": "major", "fingerprint": "no-tests", "location": { "path": ".", "lines": { "begin": 1 } } } ]' gl-code-quality-report.json > tmp.json && mv tmp.json gl-code-quality-report.json 
       fi
    artifacts:
      reports:
        codequality: gl-code-quality-report.json
      paths:
        - gl-code-quality-report.json
      when: always
    needs: ["build-task"]

static_analysis:
  image: golang:1.24-alpine
  before_script:
    - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
    - go install golang.org/x/lint/golint@latest
    - go install github.com/go-critic/go-critic/cmd/gocritic@latest
    - go install honnef.co/go/tools/cmd/staticcheck@latest
  script:
    - go vet ./... || true
    - staticcheck ./... || true
    - gocritic check ./... || true
    - gocyclo -over 15 . || true
  needs: ["build-task"]
  only:
    - master
  #  - dev

unit_tests:
  image: golang:1.24-alpine
  before_script:
    - go install github.com/jstemmer/go-junit-report@latest
  script:
    - go test -v ./... 2>&1 | go-junit-report > unit_test_results.xml || true
  artifacts:
    reports:
      junit: unit_test_results.xml
    paths:
      - unit_test_results.xml
  needs: ["build-task"]
  only:
    - master
  #  - dev

a11y:
  artifacts:
    reports:
      accessibility: gl-accessibility-report.json
    paths:
      - "$CI_PROJECT_DIR/gl-accessibility-report.json"
  after_script:
    - cd $CI_PROJECT_DIR

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"
    CI_DEBUG_TRACE: "true"
  before_script:
    - |
      # Удаляем файл если он существует
      rm -f gl-secret-detection-report.json
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json
    paths:
      - "gl-secret-detection-report.json"
  after_script:
    - cd $CI_PROJECT_DIR

sast:
  variables:
    CI_DEBUG_TRACE: "true"
  before_script:
    - |
      # Удаляем файл если он существует
      rm -f gl-sast-report.json
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - "gl-sast-report.json"

dependency_scanning:
  variables:
    CI_DEBUG_TRACE: "true"
  before_script:
    - |
      # Удаляем файл если он существует
      rm -f gl-dependency-scanning-report.json
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
    paths:
      - "gl-dependency-scanning-report.json"

test-task:
  stage: test
  script:
    - echo "test"
  needs: ["build-task"]
  only:
    - master
    - dev

deploy-task:
  stage: deploy
  script:
    - docker rm --force $IMAGE_NAME
    - docker pull $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker run -d -p 9999:9999 --name $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME
  needs: ["test-task"]
  only:
    - master
    - dev
...
