---
variables:
  IMAGE_TAG: "latest"
#  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - test
  - deploy

image: docker:latest
services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]

build-task:
  stage: build
 # variables:
   # DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG .
    - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
test-task:
  stage: test
  script:
    - echo "test"

deploy-task:
  stage: deploy
  script:
    - docker pull $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
    - docker run -d -p 9999:9999 --name $IMAGE_NAME $IMAGE_NAME
    - docker rm --force $IMAGE_NAME
...
