---
stages:
  - build
  - test
  - deploy

image: golang:1.24-alpine

build-task:
  stage: build
  script:
    - go mod download
    - CGO_ENABLED=0 GOOS=linux go build -o server

test-task:
  stage: test
  script:
    - echo "test"

deploy-task:
  stage: deploy
  script:
    - ls -la
...
